phase0:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/phase0/**'
      - 'presets/*/phase0.yaml'
      - 'pysetup/spec_builders/phase0.py'

altair:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/altair/**'
      - 'presets/*/altair.yaml'
      - 'pysetup/spec_builders/altair.py'

bellatrix:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/bellatrix/**'
      - 'presets/*/bellatrix.yaml'
      - 'pysetup/spec_builders/bellatrix.py'

capella:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/capella/**'
      - 'presets/*/capella.yaml'
      - 'pysetup/spec_builders/capella.py'

sila_deneb:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/sila_deneb/**'
      - 'presets/*/sila_deneb.yaml'
      - 'pysetup/spec_builders/sila_deneb.py'

electra:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/electra/**'
      - 'presets/*/electra.yaml'
      - 'pysetup/spec_builders/electra.py'

sila_fulu:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/sila_fulu/**'
      - 'presets/*/sila_fulu.yaml'
      - 'pysetup/spec_builders/sila_fulu.py'

gloas:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/gloas/**'
      - 'presets/*/gloas.yaml'
      - 'pysetup/spec_builders/gloas.py'

heze:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/heze/**'
      - 'presets/*/heze.yaml'
      - 'pysetup/spec_builders/heze.py'

sip6914:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/sip6914/**'
      - 'presets/*/sip6914.yaml'
      - 'pysetup/spec_builders/sip6914.py'

sip8025:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/sip8025/**'
      - 'presets/*/sip8025.yaml'
      - 'pysetup/spec_builders/sip8025.py'

sip8148:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/sip8148/**'
      - 'presets/*/sip8148.yaml'
      - 'pysetup/spec_builders/sip8148.py'

testing:
  - changed-files:
    - all-globs-to-any-file:
      - 'tests/**'

ssz:
  - changed-files:
    - any-glob-to-any-file:
      - 'ssz/**'

lightclients:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/**/light-client/**'
