categories:
  # Forks
  - title: Phase0
    when:
      label: phase0
  - title: Altair
    when:
      label: altair
  - title: Bellatrix
    when:
      label: bellatrix
  - title: Capella
    when:
      label: capella
  - title: SilaDeneb
    when:
      label: sila_deneb
  - title: Electra
    when:
      label: electra
  - title: SilaFulu
    when:
      labels:
        - sila_fulu
        - sip7594
  - title: Gloas
    when:
      labels:
        - gloas
        - sip7732
        - sip7843
        - sip7928
        - sip8061
  - title: Heze
    when:
      labels:
        - heze
        - sip7805

  # Features
  - title: SIP-6914
    when:
      label: sip6914
  - title: SIP-8025
    when:
      label: sip8025
  - title: SIP-8148
    when:
      label: sip8148

  # Testing
  - title: Testing
    when:
      label: testing

  # Dependencies
  - title: Dependencies
    when:
      label: dependencies

  # Fallback
  - title: Other

commitish: master
filter-by-commitish: true
include-pre-releases: true
sort-direction: ascending
change-title-escapes: '\<*_&'
change-template: '- $TITLE (#$NUMBER)'
template: |
  $CHANGES
