categories:
  # Forks
  - title: Phase0
    label: phase0
  - title: Altair
    label: altair
  - title: Bellatrix
    label: bellatrix
  - title: Capella
    label: capella
  - title: SilaDeneb
    label: deneb
  - title: Electra
    label: electra
  - title: SilaFulu
    labels:
      - fulu
      - sip7594
  - title: Gloas
    labels:
      - gloas
      - sip7732
      - sip7928

  # Features
  - title: SIP-6110
    label: sip6110
  - title: SIP-7441
    label: sip7441
  - title: SIP-7805
    label: sip7805
  - title: SIP-8025
    label: sip8025

  # Testing
  - title: Testing
    label: testing

  # Fallback
  - title: Other

commitish: master
filter-by-commitish: true
include-pre-releases: true
sort-direction: ascending
change-title-escapes: '\<*_&'
change-template: '- $TITLE (#$NUMBER)'
template: |
  $CHANGES
