name: Update Website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv ${{ vars.UV_VERSION }}
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          version: ${{ vars.UV_VERSION }}

      - name: Install dependencies to venv
        run: make _pyspec

      - name: Build docs
        run: make _copy_docs

      - name: Deploy
        run: uv run mkdocs gh-deploy --force
